CREATE TABLE [dbo].[ACSurvey] (
    [ACSurveyID]                                                 INT            IDENTITY (1, 1) NOT NULL,
    [Reporting Quarter:]                                         NVARCHAR (255) NULL,
    [First Name:]                                                NVARCHAR (255) NULL,
    [Last Name:]                                                 NVARCHAR (255) NULL,
    [Email:]                                                     NVARCHAR (255) NULL,
    [Project #:]                                                 NVARCHAR (255) NULL,
    [Host Site:]                                                 NVARCHAR (255) NULL,
    [List other VHCB Americorps Members Covered by this report#] NVARCHAR (255) NULL,
    [Q1: ]                                                       NVARCHAR (255) NULL,
    [Q2: ]                                                       NVARCHAR (255) NULL,
    [Q3: ]                                                       NVARCHAR (255) NULL,
    [Q4: ]                                                       NVARCHAR (MAX) NULL,
    [Q5: ]                                                       NVARCHAR (255) NULL,
    [Q6:]                                                        NVARCHAR (255) NULL,
    [Q7: ]                                                       NVARCHAR (255) NULL,
    [Q8: ]                                                       NVARCHAR (255) NULL,
    [Q9: ]                                                       NVARCHAR (255) NULL,
    [Q10:]                                                       NVARCHAR (255) NULL,
    [Q11:]                                                       NVARCHAR (255) NULL,
    [Q12: ]                                                      NVARCHAR (255) NULL,
    [Q13:]                                                       NVARCHAR (255) NULL,
    [Q14: ]                                                      NVARCHAR (255) NULL,
    [Q15:]                                                       NVARCHAR (255) NULL,
    [Q16: ]                                                      NVARCHAR (MAX) NULL,
    [Q17: ]                                                      NVARCHAR (255) NULL,
    [Q18: ]                                                      NVARCHAR (255) NULL,
    [Q19: ]                                                      NVARCHAR (255) NULL,
    [Q20: ]                                                      NVARCHAR (255) NULL,
    [Q21: ]                                                      NVARCHAR (255) NULL,
    [Q22: ]                                                      NVARCHAR (MAX) NULL,
    [Q23:]                                                       NVARCHAR (MAX) NULL,
    [Q24:]                                                       NVARCHAR (255) NULL,
    [Q25:]                                                       NVARCHAR (255) NULL,
    [Q26: ]                                                      NVARCHAR (255) NULL,
    [Q27: ]                                                      NVARCHAR (255) NULL,
    [Q28: ]                                                      NVARCHAR (255) NULL,
    [Q29: ]                                                      NVARCHAR (MAX) NULL,
    [Q30: ]                                                      NVARCHAR (255) NULL,
    [Q31:]                                                       NVARCHAR (255) NULL,
    [Q32:]                                                       NVARCHAR (MAX) NULL,
    [Q33: ]                                                      NVARCHAR (MAX) NULL,
    [Q34: ]                                                      NVARCHAR (MAX) NULL,
    [Q35: ]                                                      NVARCHAR (255) NULL,
    [Q36: ]                                                      NVARCHAR (255) NULL,
    [Q37:]                                                       NVARCHAR (255) NULL,
    [Q38:]                                                       NVARCHAR (255) NULL,
    [Q39:]                                                       NVARCHAR (255) NULL,
    [Q40: ]                                                      NVARCHAR (255) NULL,
    [Q41: ]                                                      NVARCHAR (255) NULL,
    [Q42: ]                                                      NVARCHAR (255) NULL,
    [Q43:]                                                       NVARCHAR (255) NULL,
    [Q44:]                                                       NVARCHAR (255) NULL,
    [Q45: ]                                                      NVARCHAR (255) NULL,
    [Q46:]                                                       NVARCHAR (255) NULL,
    [Q47: ]                                                      NVARCHAR (MAX) NULL,
    [RowIsActive]                                                BIT            CONSTRAINT [DF_ACSurvey_RowIsActive] DEFAULT ((1)) NOT NULL,
    [DateModified]                                               DATETIME       CONSTRAINT [DF_ACSurvey_DateModified] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_ACSurvey] PRIMARY KEY CLUSTERED ([ACSurveyID] ASC)
);

