CREATE TABLE [dbo].[AnnualAssetManag_not used] (
    [ID]                       INT            IDENTITY (1, 1) NOT NULL,
    [ProjName]                 NVARCHAR (75)  NULL,
    [F2]                       NVARCHAR (255) NULL,
    [WhollyOwned]              NVARCHAR (1)   NULL,
    [LimPartnership]           NVARCHAR (1)   NULL,
    [Yearestab]                NVARCHAR (5)   NULL,
    [NumBuild]                 FLOAT (53)     NULL,
    [NumUnits]                 FLOAT (53)     NULL,
    [F8]                       NVARCHAR (255) NULL,
    [GrossPotentialRent]       FLOAT (53)     NULL,
    [VacancyLoss]              FLOAT (53)     NULL,
    [OtherIncome]              FLOAT (53)     NULL,
    [TotalGrossIncome]         FLOAT (53)     NULL,
    [OperatingExp]             FLOAT (53)     NULL,
    [NetOperatingIncome]       FLOAT (53)     NULL,
    [DebtService]              FLOAT (53)     NULL,
    [ReplacementReserves]      NVARCHAR (255) NULL,
    [F17]                      NVARCHAR (255) NULL,
    [CashOperatingBalance]     FLOAT (53)     NULL,
    [CashOperatingReserves]    NVARCHAR (255) NULL,
    [CashReplacementReserves]  FLOAT (53)     NULL,
    [AccountsReceiveableRent]  FLOAT (53)     NULL,
    [AccountsPayableVendors]   FLOAT (53)     NULL,
    [F23]                      NVARCHAR (255) NULL,
    [MostrecentCNA]            FLOAT (53)     NULL,
    [Projectedbalance20]       NVARCHAR (255) NULL,
    [ValueDeferredMaintenance] NVARCHAR (255) NULL,
    [F27]                      NVARCHAR (255) NULL,
    [Comments]                 NVARCHAR (255) NULL
);

